apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: twitterCron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: twitter
            image: twitter

          restartPolicy: OnFailure